services:
  message-template-postgres:
    image: postgres:15
    container_name: message-template-postgres
    restart: no
    environment:
      POSTGRES_DB: quarkus
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    # Set postgres custom port to avoid port conflict with LangFuse postgres
    command: -p '5433'
    ports:
      - "5433:5433"
    volumes:
      - message-template-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quarkus"]
      interval: 5s
      timeout: 2s
      retries: 2

  message-template:
    image: quarkus-workshop/message-template:1.0.0-SNAPSHOT
    container_name: message-template-app
    restart: no
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - message-template-postgres
    ports:
      - "8080:8080"
      - "4200:4200"
    environment:
      QUARKUS_HTTP_HOST: 0.0.0.0
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_QUINOA_DEV_SERVER_PORT: 4200

      # Application Datasource (PostgreSQL)
      QUARKUS_DATASOURCE_USERNAME: quarkus
      QUARKUS_DATASOURCE_PASSWORD: quarkus
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://message-template-postgres:5433/quarkus
      QUARKUS_HIBERNATE_ORM_SCHEMA_MANAGEMENT_STRATEGY: drop-and-create
      QUARKUS_HIBERNATE_ORM_LOG_SQL: true

      # MCP configuration
      # We use HTTP transport for client-server communication in MCP context
      QUARKUS_LANGCHAIN4J_MCP_TEMPLATE_GENERATOR_TRANSPORT_TYPE: http
      # The URL of the SSE endpoint. This only applies to MCP clients using the HTTP transport.
      QUARKUS_LANGCHAIN4J_MCP_TEMPLATE_GENERATOR_URL: http://message-template:8080/mcp/sse
      # If set to true then JSON messages received/sent are logged.
      QUARKUS_MCP_SERVER_TRAFFIC_LOGGING_ENABLED: true
      # The number of characters of a text message which will be logged if traffic logging is enabled, default is 200 characters.
      QUARKUS_MCP_SERVER_TRAFFIC_LOGGING_TEXT_LIMIT: 20000

      # Ollama (runs on host)
      QUARKUS_LANGCHAIN4J_OLLAMA_CHAT_MODEL_MODEL_ID: gpt-oss
      # Global timeout for requests to LLM APIs
      QUARKUS_LANGCHAIN4J_TIMEOUT: 90s
      # The temperature to use for the chat model. Temperature is a value between 0 and 1, where lower values make the model more deterministic and higher values make it more creative.
      QUARKUS_LANGCHAIN4J_TEMPERATURE: 0.2
      QUARKUS_LANGCHAIN4J_OLLAMA_BASE_URL: http://host.docker.internal:11434
      # Enable logging of client requests and responses to/from LLM APIs
      QUARKUS_LANGCHAIN4J_LOG_REQUESTS: true
      QUARKUS_LANGCHAIN4J_LOG_RESPONSES: true

      # Enable the CORS filter. This will allow the Angular client to access the Quarkus API.
      QUARKUS_HTTP_CORS_ENABLED: true
      # The allowed origins for CORS requests. Port 4200 is the URL of the Angular client, port 6274 is from MCP-Inspector
      QUARKUS_HTTP_CORS_ORIGINS: http://localhost:4200, http://localhost:6274
      QUARKUS_HTTP_CORS_HEADERS: accept,authorization,content-type,x-requested-with
      # HTTP methods allowed for CORS.
      QUARKUS_HTTP_CORS_METHODS: POST,GET,PUT,DELETE

      QUARKUS_OTEL_ENABLED: true
      QUARKUS_OTEL_METRICS_ENABLED: true

      QUARKUS_OTEL_EXPORTER_OTLP_TRACES_HEADERS: "Authorization=Basic cGstbGYtZGY5YzBhZTYtMDAzNS00NTVhLWI3ZGItZTYyMTFhODhiYzkxOnNrLWxmLWFjNTA1ZGU2LTQ1NzctNDAwYy1hNWEwLTVlYjU1ZDhjZDQ0YQ=="
      QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://host.docker.internal:3000/api/public/otel"

      # The location of the template files WITHIN the container
      APP_RESOURCES_LOCATION: "/resources"

volumes:
  message-template-postgres-data:
